<a href="https://colab.research.google.com/github/anudaindu/Mobitel_Alarm_Fault_Prediction/blob/main/01_Data_Loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [8]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import openpyxl # Added for reading .xlsx files

Importing Data sets

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [15]:
file_path = '/content/drive/MyDrive/MobitelData/AlarmLogs20260803113740030_9.xlsx'
try:
    df = pd.read_excel(file_path)
    print(f"Dataset loaded successfully from {file_path}")
    display(df.head())
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please check the path and try again.")
except Exception as e:
    print(f"An error occurred while loading the dataset: {e}")

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Dataset loaded successfully from /content/drive/MyDrive/MobitelData/AlarmLogs20260803113740030_9.xlsx

,,Severity,Occurred On (NT),Cleared On (NT),Alarm ID,MO Name,Comment,Name,Location Information,Additional Information,...,RRU Name,Received On (ST),Request ID,Subnet,Toggling Times,Trouble Ticket ID,Type,User Label,eNodeB ID,gNodeB ID
0,Root alarm,Major,2026-07-07 09:48:01,2026-07-07 11:47:31,25952,BDBAD2_GUL00_BADULLA _HUCH_IP_Ba,-,User Plane Path Fault,"User Plane Host ID=140, PEERIP=69.16.42.6, USE...","RAT_INFO=GL, AFFECTED_RAT=GL, DID=NULL, Cumula...",...,-,2026-07-07 09:49:32,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Trunk system,-,2704,-
1,-,Major,2026-07-07 09:49:08,2026-07-07 09:49:10,25600,GLPIT2_G_Pitigala2__9__Ab,-,Monitoring Device Maintenance Link Failure,"Cabinet No.=0, Subrack No.=7, Slot No.=0, Boar...","RAT_INFO=G, AFFECTED_RAT=G, DID=AUTODID_201808...",...,-,2026-07-07 09:49:34,-,ROOT/RAN Subnet/MBSC,0,-,Communication system,-,-,-
2,-,Major,2026-07-07 09:49:14,2026-07-07 09:49:16,25600,GLPIT2_G_Pitigala2__9__Ab,-,Monitoring Device Maintenance Link Failure,"Cabinet No.=0, Subrack No.=7, Slot No.=0, Boar...","RAT_INFO=G, AFFECTED_RAT=G, DID=AUTODID_201808...",...,-,2026-07-07 09:49:40,-,ROOT/RAN Subnet/MBSC,0,-,Communication system,-,-,-
3,-,Major,2026-07-07 09:49:19,2026-07-07 09:49:21,25600,GLPIT2_G_Pitigala2__9__Ab,-,Monitoring Device Maintenance Link Failure,"Cabinet No.=0, Subrack No.=7, Slot No.=0, Boar...","RAT_INFO=G, AFFECTED_RAT=G, DID=AUTODID_201808...",...,-,2026-07-07 09:49:44,-,ROOT/RAN Subnet/MBSC,0,-,Communication system,-,-,-
4,-,Major,2026-07-07 09:49:23,2026-07-07 09:49:25,25600,GLPIT2_G_Pitigala2__9__Ab,-,Monitoring Device Maintenance Link Failure,"Cabinet No.=0, Subrack No.=7, Slot No.=0, Boar...","RAT_INFO=G, AFFECTED_RAT=G, DID=AUTODID_201808...",...,-,2026-07-07 09:49:48,-,ROOT/RAN Subnet/MBSC,0,-,Communication system,-,-,-

### Combining Multiple Excel Files

combining excel files in mobi_data2 file to get a vast amount of combined data to analysis

In [27]:
import os

# Define the directory where your Excel files are located
data_directory = '/content/drive/MyDrive/MobitelData/mobi_data2'

# List all files in the directory that end with .xlsx
excel_files = [f for f in os.listdir(data_directory) if f.endswith('.xlsx')]
excel_files.sort() # Optional: Sort files if order matters (e.g., by date in filename)

# Initialize an empty list to store individual DataFrames
all_dfs = []

print(f"Found {len(excel_files)} Excel files in '{data_directory}':")

# Loop through each Excel file and append its data to the list
for i, file_name in enumerate(excel_files):
    file_path = os.path.join(data_directory, file_name)
    try:
        # Read the Excel file, assuming the actual header starts at row index 4 (5th row)
        df_temp = pd.read_excel(file_path, header=4)
        all_dfs.append(df_temp)
        print(f"  - Successfully loaded '{file_name}' (shape: {df_temp.shape})")
    except Exception as e:
        print(f"  - Error loading '{file_name}': {e}")

# Concatenate all DataFrames in the list into a single DataFrame
if all_dfs:
    combined_df = pd.concat(all_dfs, ignore_index=True)
    print(f"\nSuccessfully combined {len(all_dfs)} files into a single DataFrame.")
    print("Combined DataFrame shape:", combined_df.shape)
    print("First 5 rows of the combined DataFrame:")
    display(combined_df.head())
else:
    print("No Excel files were successfully loaded and combined.")

# Update the main 'df' variable to hold the combined DataFrame
df = combined_df

Found 10 Excel files in '/content/drive/MyDrive/MobitelData/mobi_data2':

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  - Successfully loaded 'AlarmLogs20260803113740030_10.xlsx' (shape: (99996, 44))

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  - Successfully loaded 'AlarmLogs20260803113740030_11.xlsx' (shape: (99996, 44))
  - Successfully loaded 'AlarmLogs20260803113740030_2.xlsx' (shape: (99996, 44))
  - Successfully loaded 'AlarmLogs20260803113740030_3.xlsx' (shape: (99996, 44))

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  - Successfully loaded 'AlarmLogs20260803113740030_4.xlsx' (shape: (99996, 44))

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  - Successfully loaded 'AlarmLogs20260803113740030_5.xlsx' (shape: (99996, 44))

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  - Successfully loaded 'AlarmLogs20260803113740030_6.xlsx' (shape: (99996, 44))
  - Successfully loaded 'AlarmLogs20260803113740030_7.xlsx' (shape: (99996, 44))

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  - Successfully loaded 'AlarmLogs20260803113740030_8.xlsx' (shape: (99996, 44))

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  - Successfully loaded 'AlarmLogs20260803113740030_9.xlsx' (shape: (99996, 44))

Successfully combined 10 files into a single DataFrame.
Combined DataFrame shape: (999960, 205)
First 5 rows of the combined DataFrame:

,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba, Local Cell ID=82, Cell Name=BDPAS2-M-L85-C1, Cell FDD TDD indication=CELL_FDD",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba, Local Cell ID=82, Cell FDD TDD indication=FDD, NB-IoT Cell Flag=FALSE, Cell Name=BDPAS2-M-L85-C1, eNodeB ID=3537, Cell ID=83, Specific Problem=RF Power OFF","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulative Duration(s)=90, eNodeBId=3537",...,2026-07-06 16:39:31,Environment system,2026-07-07 09:49:19,2026-07-07 09:49:21,0 hours 0 minutes 2 seconds,2026-07-08 00:32:54,&6161908-40663&,6161908,1139391082,2026-07-07 09:49:44
0,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Root alarm,Critical,2026-07-07 19:28:29,2026-07-07 19:29:26,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Root alarm,Critical,2026-07-07 19:29:26,2026-07-07 19:30:39,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Root alarm,Critical,2026-07-07 19:29:50,2026-07-07 19:30:57,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Basic Analysis of Data

In [28]:
df.head()

,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba, Local Cell ID=82, Cell Name=BDPAS2-M-L85-C1, Cell FDD TDD indication=CELL_FDD",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba, Local Cell ID=82, Cell FDD TDD indication=FDD, NB-IoT Cell Flag=FALSE, Cell Name=BDPAS2-M-L85-C1, eNodeB ID=3537, Cell ID=83, Specific Problem=RF Power OFF","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulative Duration(s)=90, eNodeBId=3537",...,2026-07-06 16:39:31,Environment system,2026-07-07 09:49:19,2026-07-07 09:49:21,0 hours 0 minutes 2 seconds,2026-07-08 00:32:54,&6161908-40663&,6161908,1139391082,2026-07-07 09:49:44
0,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Root alarm,Critical,2026-07-07 19:28:29,2026-07-07 19:29:26,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Root alarm,Critical,2026-07-07 19:29:26,2026-07-07 19:30:39,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Root alarm,Critical,2026-07-07 19:29:50,2026-07-07 19:30:57,29240.0,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999960 entries, 0 to 999959
Columns: 205 entries, Root alarm to 2026-07-07 09:49:44
dtypes: float64(27), int64(1), object(177)
memory usage: 1.5+ GB

In [18]:
df.shape

(100000, 44)

In [19]:
df.columns

Index([' ', 'Severity', 'Occurred On (NT)', 'Cleared On (NT)', 'Alarm ID',
       'MO Name', 'Comment', 'Name', 'Location Information',
       'Additional Information', 'Alarm Duration', 'Alarm Source',
       'Acknowledged By', 'Acknowledged On (ST)', 'Acknowledgement Status',
       'Associated Alarm Group ID', 'Auto Clear', 'BBU Name',
       'Clearance Status', 'Clearance Type', 'Cleared By',
       'Common Alarm Identifier', 'Dev Root CSN',
       'Equipment Alarm Serial Number', 'External Resource ID', 'Link Name',
       'Link Type', 'Log Serial Number', 'Maintenance Region',
       'Maintenance Status', 'NE Address', 'NE Type', 'Object Type',
       'Operation Impact Flag', 'RRU Name', 'Received On (ST)', 'Request ID',
       'Subnet', 'Toggling Times', 'Trouble Ticket ID', 'Type', 'User Label',
       'eNodeB ID', 'gNodeB ID'],
      dtype='object')

Data Cleaning

In [30]:
df.isnull().sum()

Root alarm             599976
Critical               799968
2026-07-07 19:26:47    899964
2026-07-07 19:27:57    899964
29240                  899964
                        ...
2026-07-08 00:32:54    899964
&6161908-40663&        899964
6161908                899964
1139391082             899964
2026-07-07 09:49:44    899964
Length: 205, dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

In [32]:
df = df.drop_duplicates()

To treat `'-'` as missing values, we'll replace all occurrences of `'-'` in the DataFrame with `np.nan`.

In [34]:
df.replace('-', np.nan, inplace=True)
print("'-' values replaced with NaN.")

# Display the count of null values again after replacement
display(df.isnull().sum())

/tmp/ipykernel_2852/3962868886.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('-', np.nan, inplace=True)

'-' values replaced with NaN.

Root alarm             780424
Critical               799968
2026-07-07 19:26:47    899964
2026-07-07 19:27:57    899964
29240                  899964
                        ...
2026-07-08 00:32:54    899964
&6161908-40663&        899964
6161908                899964
1139391082             899964
2026-07-07 09:49:44    899964
Length: 205, dtype: int64