In [72]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [73]:
import pandas as pd

file_path = '/content/drive/MyDrive/MobitelData/mobi_data2_combined.csv'
df = pd.read_csv(file_path, low_memory=False)
display(df.head())

,,Severity,Occurred On (NT),Cleared On (NT),Alarm ID,MO Name,Comment,Name,Location Information,Additional Information,...,RRU Name,Received On (ST),Request ID,Subnet,Toggling Times,Trouble Ticket ID,Type,User Label,eNodeB ID,gNodeB ID
0,Root alarm,Critical,2026-07-07 19:24:39,2026-07-07 19:26:21,29240,"eNodeB Function Name=KLELU1_L_Eluwila_IP_Pi, L...",-,Cell Unavailable,"eNodeB Function Name=KLELU1_L_Eluwila_IP_Pi, L...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,4636,-
1,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:30,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
2,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:39,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
3,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-

In [74]:
new_column_names = [
    'alarm_type',
    'severity',
    'occurred_on',
    'cleared_on',
    'alarm_id',
    'mo_name',
    'comment',
    'alarm_name',
    'location_information',
    'additional_information',
    'alarm_duration',
    'alarm_source',
    'acknowledged_by',
    'acknowledged_on',
    'acknowledgement_status',
    'associated_alarm_group_id',
    'auto_clear',
    'bbu_name',
    'clearance_status',
    'clearance_type',
    'cleared_by',
    'common_alarm_identifier',
    'dev_root_csn',
    'equipment_alarm_serial_number',
    'external_resource_id',
    'link_name',
    'link_type',
    'log_serial_number',
    'maintenance_region',
    'maintenance_status',
    'ne_address',
    'ne_type',
    'object_type',
    'operation_impact_flag',
    'rru_name',
    'received_on',
    'request_id',
    'subnet',
    'toggling_times',
    'trouble_ticket_id',
    'type',
    'user_label',
    'enodeb_id',
    'gnodeb_id'
]

df.columns = new_column_names
display(df.head())

,alarm_type,severity,occurred_on,cleared_on,alarm_id,mo_name,comment,alarm_name,location_information,additional_information,...,rru_name,received_on,request_id,subnet,toggling_times,trouble_ticket_id,type,user_label,enodeb_id,gnodeb_id
0,Root alarm,Critical,2026-07-07 19:24:39,2026-07-07 19:26:21,29240,"eNodeB Function Name=KLELU1_L_Eluwila_IP_Pi, L...",-,Cell Unavailable,"eNodeB Function Name=KLELU1_L_Eluwila_IP_Pi, L...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,4636,-
1,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:30,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
2,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:39,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
3,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-

In [75]:
df = df.iloc[1:].copy()
display(df.head())

,alarm_type,severity,occurred_on,cleared_on,alarm_id,mo_name,comment,alarm_name,location_information,additional_information,...,rru_name,received_on,request_id,subnet,toggling_times,trouble_ticket_id,type,user_label,enodeb_id,gnodeb_id
1,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:30,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
2,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:39,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
3,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
5,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-

Converting date time columns to datetimeobjects.

In [76]:
df['occurred_on'] = pd.to_datetime(df['occurred_on'], errors='coerce')
df['cleared_on'] = pd.to_datetime(df['cleared_on'], errors='coerce')

# Display the DataFrame info to verify the data types
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 1 to 999999
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   alarm_type                     999999 non-null  object
 1   severity                       999999 non-null  object
 2   occurred_on                    999999 non-null  datetime64[ns]
 3   cleared_on                     999999 non-null  datetime64[ns]
 4   alarm_id                       999999 non-null  int64
 5   mo_name                        999999 non-null  object
 6   comment                        999999 non-null  object
 7   alarm_name                     999999 non-null  object
 8   location_information           999999 non-null  object
 9   additional_information         999999 non-null  object
 10  alarm_duration                 999999 non-null  object
 11  alarm_source                   999999 non-null  object
 12  acknowledged_by                999999 non-null  object
 13  acknowledged_on                999999 non-null  object
 14  acknowledgement_status         999999 non-null  object
 15  associated_alarm_group_id      999999 non-null  object
 16  auto_clear                     999999 non-null  object
 17  bbu_name                       999999 non-null  object
 18  clearance_status               999999 non-null  object
 19  clearance_type                 999999 non-null  object
 20  cleared_by                     999999 non-null  object
 21  common_alarm_identifier        4092 non-null    object
 22  dev_root_csn                   999999 non-null  object
 23  equipment_alarm_serial_number  999999 non-null  int64
 24  external_resource_id           999999 non-null  object
 25  link_name                      999999 non-null  object
 26  link_type                      999999 non-null  object
 27  log_serial_number              999999 non-null  int64
 28  maintenance_region             999999 non-null  object
 29  maintenance_status             999999 non-null  object
 30  ne_address                     999999 non-null  object
 31  ne_type                        999999 non-null  object
 32  object_type                    999999 non-null  object
 33  operation_impact_flag          999999 non-null  object
 34  rru_name                       993266 non-null  object
 35  received_on                    999999 non-null  object
 36  request_id                     999999 non-null  object
 37  subnet                         999999 non-null  object
 38  toggling_times                 999999 non-null  int64
 39  trouble_ticket_id              999999 non-null  object
 40  type                           999999 non-null  object
 41  user_label                     999999 non-null  object
 42  enodeb_id                      999999 non-null  object
 43  gnodeb_id                      999999 non-null  object
dtypes: datetime64[ns](2), int64(4), object(38)
memory usage: 335.7+ MB

None

In [77]:
df['received_on'] = pd.to_datetime(df['received_on'], errors='coerce')
df['acknowledged_on'] = pd.to_datetime(df['acknowledged_on'], errors='coerce')

# Display the DataFrame info again to verify all datetime conversions
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 1 to 999999
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   alarm_type                     999999 non-null  object
 1   severity                       999999 non-null  object
 2   occurred_on                    999999 non-null  datetime64[ns]
 3   cleared_on                     999999 non-null  datetime64[ns]
 4   alarm_id                       999999 non-null  int64
 5   mo_name                        999999 non-null  object
 6   comment                        999999 non-null  object
 7   alarm_name                     999999 non-null  object
 8   location_information           999999 non-null  object
 9   additional_information         999999 non-null  object
 10  alarm_duration                 999999 non-null  object
 11  alarm_source                   999999 non-null  object
 12  acknowledged_by                999999 non-null  object
 13  acknowledged_on                999999 non-null  datetime64[ns]
 14  acknowledgement_status         999999 non-null  object
 15  associated_alarm_group_id      999999 non-null  object
 16  auto_clear                     999999 non-null  object
 17  bbu_name                       999999 non-null  object
 18  clearance_status               999999 non-null  object
 19  clearance_type                 999999 non-null  object
 20  cleared_by                     999999 non-null  object
 21  common_alarm_identifier        4092 non-null    object
 22  dev_root_csn                   999999 non-null  object
 23  equipment_alarm_serial_number  999999 non-null  int64
 24  external_resource_id           999999 non-null  object
 25  link_name                      999999 non-null  object
 26  link_type                      999999 non-null  object
 27  log_serial_number              999999 non-null  int64
 28  maintenance_region             999999 non-null  object
 29  maintenance_status             999999 non-null  object
 30  ne_address                     999999 non-null  object
 31  ne_type                        999999 non-null  object
 32  object_type                    999999 non-null  object
 33  operation_impact_flag          999999 non-null  object
 34  rru_name                       993266 non-null  object
 35  received_on                    999999 non-null  datetime64[ns]
 36  request_id                     999999 non-null  object
 37  subnet                         999999 non-null  object
 38  toggling_times                 999999 non-null  int64
 39  trouble_ticket_id              999999 non-null  object
 40  type                           999999 non-null  object
 41  user_label                     999999 non-null  object
 42  enodeb_id                      999999 non-null  object
 43  gnodeb_id                      999999 non-null  object
dtypes: datetime64[ns](4), int64(4), object(36)
memory usage: 335.7+ MB

None

Standardizing the column names

In [78]:
import re

def standardize_column_name(col_name):
    # Convert to lowercase
    col_name = col_name.lower()
    # Replace spaces with underscores
    col_name = col_name.replace(' ', '_')
    # Remove any characters that are not alphanumeric or underscores
    col_name = re.sub(r'[^a-z0-9_]', '', col_name)
    return col_name

df.columns = [standardize_column_name(col) for col in df.columns]

print("Standardized column names:")
display(df.columns.tolist())

Standardized column names:

['alarm_type',
 'severity',
 'occurred_on',
 'cleared_on',
 'alarm_id',
 'mo_name',
 'comment',
 'alarm_name',
 'location_information',
 'additional_information',
 'alarm_duration',
 'alarm_source',
 'acknowledged_by',
 'acknowledged_on',
 'acknowledgement_status',
 'associated_alarm_group_id',
 'auto_clear',
 'bbu_name',
 'clearance_status',
 'clearance_type',
 'cleared_by',
 'common_alarm_identifier',
 'dev_root_csn',
 'equipment_alarm_serial_number',
 'external_resource_id',
 'link_name',
 'link_type',
 'log_serial_number',
 'maintenance_region',
 'maintenance_status',
 'ne_address',
 'ne_type',
 'object_type',
 'operation_impact_flag',
 'rru_name',
 'received_on',
 'request_id',
 'subnet',
 'toggling_times',
 'trouble_ticket_id',
 'type',
 'user_label',
 'enodeb_id',
 'gnodeb_id']

Data Cleaning

Duplication checking and removing - no duplications are found,


edit:there is a data duplication found and it removed manually.

In [79]:
initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
duplicates_removed = initial_rows - df.shape[0]

print(f"Number of duplicate rows removed: {duplicates_removed}")
print(f"New DataFrame shape: {df.shape}")
display(df.head())

Number of duplicate rows removed: 0
New DataFrame shape: (999999, 44)

,alarm_type,severity,occurred_on,cleared_on,alarm_id,mo_name,comment,alarm_name,location_information,additional_information,...,rru_name,received_on,request_id,subnet,toggling_times,trouble_ticket_id,type,user_label,enodeb_id,gnodeb_id
1,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:30,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
2,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:39,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
3,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
5,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-

Handling missing values

### Evaluating Missing Values with '-' as Missing Data

As suggested, we will now consider '-' as a missing value and replace it with `NaN` across the DataFrame before re-checking for missing values.

In [80]:
# Replace all '-' values with NaN in the DataFrame
df.replace('-', pd.NA, inplace=True)

# Re-calculate missing values after replacing '-' with NaN
missing_values_rechecked = df.isnull().sum()
missing_values_rechecked = missing_values_rechecked[missing_values_rechecked > 0].sort_values(ascending=False)

print("Columns with missing values (including '-' as NaN) and their counts:")
display(missing_values_rechecked)

# Display the DataFrame info again to see updated counts
display(df.info())

Columns with missing values (including '-' as NaN) and their counts:

maintenance_region         999999
link_type                  999999
trouble_ticket_id          999999
user_label                 999999
link_name                  999999
operation_impact_flag      999999
request_id                 999999
comment                    999545
common_alarm_identifier    995907
gnodeb_id                  993316
rru_name                   972723
alarm_type                 440422
enodeb_id                  425701
bbu_name                   423854
dev_root_csn               405768
object_type                241266
additional_information     170627
location_information          130
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 1 to 999999
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   alarm_type                     559577 non-null  object
 1   severity                       999999 non-null  object
 2   occurred_on                    999999 non-null  datetime64[ns]
 3   cleared_on                     999999 non-null  datetime64[ns]
 4   alarm_id                       999999 non-null  int64
 5   mo_name                        999999 non-null  object
 6   comment                        454 non-null     object
 7   alarm_name                     999999 non-null  object
 8   location_information           999869 non-null  object
 9   additional_information         829372 non-null  object
 10  alarm_duration                 999999 non-null  object
 11  alarm_source                   999999 non-null  object
 12  acknowledged_by                999999 non-null  object
 13  acknowledged_on                999999 non-null  datetime64[ns]
 14  acknowledgement_status         999999 non-null  object
 15  associated_alarm_group_id      999999 non-null  object
 16  auto_clear                     999999 non-null  object
 17  bbu_name                       576145 non-null  object
 18  clearance_status               999999 non-null  object
 19  clearance_type                 999999 non-null  object
 20  cleared_by                     999999 non-null  object
 21  common_alarm_identifier        4092 non-null    object
 22  dev_root_csn                   594231 non-null  object
 23  equipment_alarm_serial_number  999999 non-null  int64
 24  external_resource_id           999999 non-null  object
 25  link_name                      0 non-null       object
 26  link_type                      0 non-null       object
 27  log_serial_number              999999 non-null  int64
 28  maintenance_region             0 non-null       object
 29  maintenance_status             999999 non-null  object
 30  ne_address                     999999 non-null  object
 31  ne_type                        999999 non-null  object
 32  object_type                    758733 non-null  object
 33  operation_impact_flag          0 non-null       object
 34  rru_name                       27276 non-null   object
 35  received_on                    999999 non-null  datetime64[ns]
 36  request_id                     0 non-null       object
 37  subnet                         999999 non-null  object
 38  toggling_times                 999999 non-null  int64
 39  trouble_ticket_id              0 non-null       object
 40  type                           999999 non-null  object
 41  user_label                     0 non-null       object
 42  enodeb_id                      574298 non-null  object
 43  gnodeb_id                      6683 non-null    object
dtypes: datetime64[ns](4), int64(4), object(36)
memory usage: 335.7+ MB

None

### Droping irrelevant columns based on Threshold

we will now drop columns that have more than 95% missing values, with the exception of `gnodeb_id` which is to be retained. For the remaining columns with missing values, including `gnodeb_id`, we will fill them appropriately.


`gnodeb_id` is required for 5G connection detections therefore it is retained.

In [81]:
total_rows = df.shape[0]
missing_percentage = (df.isnull().sum() / total_rows) * 100

# Identify columns to drop (more than 95% missing) but exclude 'gnodeb_id'
columns_to_drop = missing_percentage[missing_percentage > 95].index.tolist()

if 'gnodeb_id' in columns_to_drop:
    columns_to_drop.remove('gnodeb_id')
    print("Retaining 'gnodeb_id' as per user request, even though it has >95% missing values.")

if columns_to_drop:
    df.drop(columns=columns_to_drop, inplace=True)
    print(f"Dropped columns with >95% missing values (excluding gnodeb_id): {columns_to_drop}")
else:
    print("No columns to drop based on the >95% missing value threshold (excluding gnodeb_id).")

# Now, re-evaluate missing values and fill them for remaining columns
# For object columns, fill with 'Unknown'
for col in df.select_dtypes(include=['object']).columns:
    if df[col].isnull().any():
        df[col].fillna('Unknown', inplace=True)

# For other types (e.g., numeric), we might need different strategies, but for now assuming object types cover the rest.
# If there are datetime columns with NaT, they will remain as such, which is acceptable.

print("\nMissing values after dropping columns and filling object types:")
missing_values_final = df.isnull().sum()
missing_values_final = missing_values_final[missing_values_final > 0].sort_values(ascending=False)

if missing_values_final.empty:
    print("All missing values have been handled.")
else:
    display(missing_values_final)

display(df.head())

Retaining 'gnodeb_id' as per user request, even though it has >95% missing values.
Dropped columns with >95% missing values (excluding gnodeb_id): ['comment', 'common_alarm_identifier', 'link_name', 'link_type', 'maintenance_region', 'operation_impact_flag', 'rru_name', 'request_id', 'trouble_ticket_id', 'user_label']

/tmp/ipykernel_721/2026937173.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna('Unknown', inplace=True)

Missing values after dropping columns and filling object types:
All missing values have been handled.

,alarm_type,severity,occurred_on,cleared_on,alarm_id,mo_name,alarm_name,location_information,additional_information,alarm_duration,...,maintenance_status,ne_address,ne_type,object_type,received_on,subnet,toggling_times,type,enodeb_id,gnodeb_id
1,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 0 minutes 10 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:26:30,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown
2,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 22 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:26:39,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown
3,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 10 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:27:10,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 3 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:27:16,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown
5,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 10 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:27:16,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown

In [82]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 1 to 999999
Data columns (total 34 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   alarm_type                     999999 non-null  object
 1   severity                       999999 non-null  object
 2   occurred_on                    999999 non-null  datetime64[ns]
 3   cleared_on                     999999 non-null  datetime64[ns]
 4   alarm_id                       999999 non-null  int64
 5   mo_name                        999999 non-null  object
 6   alarm_name                     999999 non-null  object
 7   location_information           999999 non-null  object
 8   additional_information         999999 non-null  object
 9   alarm_duration                 999999 non-null  object
 10  alarm_source                   999999 non-null  object
 11  acknowledged_by                999999 non-null  object
 12  acknowledged_on                999999 non-null  datetime64[ns]
 13  acknowledgement_status         999999 non-null  object
 14  associated_alarm_group_id      999999 non-null  object
 15  auto_clear                     999999 non-null  object
 16  bbu_name                       999999 non-null  object
 17  clearance_status               999999 non-null  object
 18  clearance_type                 999999 non-null  object
 19  cleared_by                     999999 non-null  object
 20  dev_root_csn                   999999 non-null  object
 21  equipment_alarm_serial_number  999999 non-null  int64
 22  external_resource_id           999999 non-null  object
 23  log_serial_number              999999 non-null  int64
 24  maintenance_status             999999 non-null  object
 25  ne_address                     999999 non-null  object
 26  ne_type                        999999 non-null  object
 27  object_type                    999999 non-null  object
 28  received_on                    999999 non-null  datetime64[ns]
 29  subnet                         999999 non-null  object
 30  toggling_times                 999999 non-null  int64
 31  type                           999999 non-null  object
 32  enodeb_id                      999999 non-null  object
 33  gnodeb_id                      999999 non-null  object
dtypes: datetime64[ns](4), int64(4), object(26)
memory usage: 259.4+ MB

None

### Dropping Irrelevant Columns

Based on the provided reasons, the following columns are considered irrelevant for the analysis and will be dropped:

Column	Reason

acknowledged_by	Human operator.

acknowledged_on	Action taken after alarm.

acknowledgement_status	Administrative.

cleared_by	After the alarm.

associated_alarm_group_id	Internal system ID.

auto_clear	System configuration.

clearance_status	After the event.

clearance_type	Administrative.

dev_root_csn	Internal identifier.

equipment_alarm_serial_number	Unique ID, not predictive.

external_resource_id	Internal reference.

log_serial_number	Unique log ID.

toggling_times	Usually not useful initially.

In [83]:
columns_to_drop_irrelevant = [
    'acknowledged_by',
    'acknowledged_on',
    'acknowledgement_status',
    'cleared_by',
    'associated_alarm_group_id',
    'auto_clear',
    'clearance_status',
    'clearance_type',
    'dev_root_csn',
    'equipment_alarm_serial_number',
    'external_resource_id',
    'log_serial_number',
    'toggling_times',
    'bbu_name',
    'cleared_on',
    'ne_address'
]

# Filter out columns that do not exist in the DataFrame
columns_to_drop_existing = [col for col in columns_to_drop_irrelevant if col in df.columns]

# Drop the identified irrelevant columns that actually exist
if columns_to_drop_existing:
    df.drop(columns=columns_to_drop_existing, inplace=True)
    print(f"Dropped irrelevant columns: {columns_to_drop_existing}")
else:
    print("No additional irrelevant columns to drop from the current DataFrame.")

# Display the DataFrame info and head to show the changes
display(df.info())
display(df.head())

Dropped irrelevant columns: ['acknowledged_by', 'acknowledged_on', 'acknowledgement_status', 'cleared_by', 'associated_alarm_group_id', 'auto_clear', 'clearance_status', 'clearance_type', 'dev_root_csn', 'equipment_alarm_serial_number', 'external_resource_id', 'log_serial_number', 'toggling_times', 'bbu_name', 'cleared_on', 'ne_address']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 1 to 999999
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   alarm_type              999999 non-null  object
 1   severity                999999 non-null  object
 2   occurred_on             999999 non-null  datetime64[ns]
 3   alarm_id                999999 non-null  int64
 4   mo_name                 999999 non-null  object
 5   alarm_name              999999 non-null  object
 6   location_information    999999 non-null  object
 7   additional_information  999999 non-null  object
 8   alarm_duration          999999 non-null  object
 9   alarm_source            999999 non-null  object
 10  maintenance_status      999999 non-null  object
 11  ne_type                 999999 non-null  object
 12  object_type             999999 non-null  object
 13  received_on             999999 non-null  datetime64[ns]
 14  subnet                  999999 non-null  object
 15  type                    999999 non-null  object
 16  enodeb_id               999999 non-null  object
 17  gnodeb_id               999999 non-null  object
dtypes: datetime64[ns](2), int64(1), object(15)
memory usage: 137.3+ MB

None

,alarm_type,severity,occurred_on,alarm_id,mo_name,alarm_name,location_information,additional_information,alarm_duration,alarm_source,maintenance_status,ne_type,object_type,received_on,subnet,type,enodeb_id,gnodeb_id
1,Root alarm,Critical,2026-07-07 19:26:23,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 0 minutes 10 seconds,BDPAS2_GULM0_Passara_town_Ba,NORMAL,BTS3900,Cell,2026-07-07 19:26:30,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,Signaling system,3537,Unknown
2,Root alarm,Critical,2026-07-07 19:26:14,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 22 seconds,BDPAS2_GULM0_Passara_town_Ba,NORMAL,BTS3900,Cell,2026-07-07 19:26:39,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,Signaling system,3537,Unknown
3,Root alarm,Critical,2026-07-07 19:26:47,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 10 seconds,BDPAS2_GULM0_Passara_town_Ba,NORMAL,BTS3900,Cell,2026-07-07 19:27:10,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,Signaling system,3537,Unknown
4,Root alarm,Critical,2026-07-07 19:26:47,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 3 seconds,BDPAS2_GULM0_Passara_town_Ba,NORMAL,BTS3900,Cell,2026-07-07 19:27:16,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,Signaling system,3537,Unknown
5,Root alarm,Critical,2026-07-07 19:26:47,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 10 seconds,BDPAS2_GULM0_Passara_town_Ba,NORMAL,BTS3900,Cell,2026-07-07 19:27:16,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,Signaling system,3537,Unknown

checking a relationship between alarm_id and alarm_name

In [84]:
df.groupby('alarm_name')['alarm_id'].nunique().sort_values(ascending=False).head(20)

alarm_name
Extend Alarm                                        4
No response from the OCS                            2
Mains Input Out of Range                            2
S1ap Link Down                                      2
Cell Capability Degraded                            2
DNS Link Down                                       2
Cell Unavailable                                    2
License is about to use up                          2
SCTP Link Congestion                                2
Mains Failure                                       2
SCTP Link Fault                                     2
License File Expiring Precaution                    2
RF Out of Service                                   2
GTPC Tunnel Path Broken                             2
No response from the RADIUS accounting server       2
SGsAP Destination IP Address Inaccessible           2
No response from the PCRF                           2
Service Center and Service Communication Failure    2
M3UA Link Fault                                     2
IP PM Activation Failure                            2
Name: alarm_id, dtype: int64

### Fixing Data Types for Memory Optimization

To improve memory efficiency and ensure appropriate data representation, we will now optimize the data types of the DataFrame columns. This involves:

1.  **Downcasting Numerical Columns:** Converting integer columns to the smallest possible integer type (e.g., `int64` to `int32`, `int16`, or `int8`) if their value range permits.
2.  **Converting Object Columns to Categorical:** Transforming `object` type columns that are essentially categorical into `category` dtype. This is particularly useful for columns that were kept as is and were not explicitly label-encoded (e.g., `location_information`, `additional_information`, `enodeb_id`, `gnodeb_id`).

In [106]:
# Downcast numerical columns to more memory-efficient types
for col in df.select_dtypes(include=['int64', 'int32']).columns:
    # Using pd.to_numeric with downcast='integer' is a safe way to do this
    # It will only downcast if no precision is lost
    df[col] = pd.to_numeric(df[col], downcast='integer')

print("Numerical columns downcasted for memory optimization.")

# Convert remaining 'object' type columns (that are not intended for further string processing)
# to 'category' dtype for memory efficiency
object_cols_to_convert_to_category = [
    'location_information',
    'additional_information',
    'enodeb_id',
    'gnodeb_id'
]

for col in object_cols_to_convert_to_category:
    if col in df.columns:
        # Ensure we only convert if the column is currently of object type
        if df[col].dtype == 'object':
            df[col] = df[col].astype('category')
            print(f"Column '{col}' converted to 'category' type.")
        else:
            print(f"Column '{col}' is not of 'object' type, skipping category conversion.")
    else:
        print(f"Column '{col}' not found, skipping category conversion.")

print("\nDataFrame info after data type optimization:")
display(df.info())
display(df.head())

Numerical columns downcasted for memory optimization.
Column 'location_information' is not of 'object' type, skipping category conversion.
Column 'additional_information' is not of 'object' type, skipping category conversion.
Column 'enodeb_id' is not of 'object' type, skipping category conversion.
Column 'gnodeb_id' is not of 'object' type, skipping category conversion.

DataFrame info after data type optimization:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 1 to 999999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   alarm_id                    999999 non-null  int32
 1   location_information        999999 non-null  category
 2   additional_information      999999 non-null  category
 3   enodeb_id                   999999 non-null  category
 4   gnodeb_id                   999999 non-null  category
 5   alarm_type_encoded          999999 non-null  int8
 6   severity_encoded            999999 non-null  int8
 7   occurred_on_hour            999999 non-null  int8
 8   occurred_on_day             999999 non-null  int8
 9   occurred_on_weekday         999999 non-null  int8
 10  occurred_on_month           999999 non-null  int8
 11  mo_name_encoded             999999 non-null  int16
 12  alarm_name_encoded          999999 non-null  int16
 13  alarm_duration_minutes      999999 non-null  float64
 14  alarm_source_encoded        999999 non-null  int16
 15  maintenance_status_encoded  999999 non-null  int8
 16  ne_type_encoded             999999 non-null  int8
 17  object_type_encoded         999999 non-null  int8
 18  received_on_hour            999999 non-null  int8
 19  received_on_day             999999 non-null  int8
 20  received_on_weekday         999999 non-null  int8
 21  received_on_month           999999 non-null  int8
 22  subnet_encoded              999999 non-null  int8
 23  type_encoded                999999 non-null  int8
dtypes: category(4), float64(1), int16(3), int32(1), int8(15)
memory usage: 54.2 MB

None

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,alarm_source_encoded,maintenance_status_encoded,ne_type_encoded,object_type_encoded,received_on_hour,received_on_day,received_on_weekday,received_on_month,subnet_encoded,type_encoded
1,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10
2,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10
3,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10
4,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10
5,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10

### Data Encoding

Following the defined strategy, we will now encode the relevant columns. We will use `LabelEncoder` for nominal categorical features, explicit mapping for ordinal features, and extract temporal features from datetime columns. `LabelEncoder` instances will be stored in a dictionary for potential future use (e.g., during prediction on new data).

In [86]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Dictionary to store LabelEncoders for future use
label_encoders = {}

print("Starting data encoding...")

Starting data encoding...

#### 1. `alarm_type` -> Label Encoding

In [87]:
if 'alarm_type' in df.columns:
    le_alarm_type = LabelEncoder()
    # Ensure all unique values from the column are used for fitting
    df['alarm_type_encoded'] = le_alarm_type.fit_transform(df['alarm_type'])
    label_encoders['alarm_type'] = le_alarm_type
    print(f"Mapping for 'alarm_type':")
    for i, item in enumerate(le_alarm_type.classes_):
        print(f"  {item} -> {i}")
    df.drop(columns=['alarm_type'], inplace=True)
else:
    print("'alarm_type' column not found, skipping encoding.")

Mapping for 'alarm_type':
  Comments -> 0
  Correlative alarm -> 1
  Correlative alarm / Comments -> 2
  Correlative alarm / Toggle alarm -> 3
  Root alarm -> 4
  Root alarm / Comments -> 5
  Root alarm / Toggle alarm -> 6
  Toggle alarm -> 7
  Unknown -> 8

#### 2. `severity` -> Ordinal Encoding

In [88]:
if 'severity' in df.columns:
    severity_mapping = {
        'Critical': 4,
        'Major': 3,
        'Minor': 2,
        'Warning': 1,
        'Unknown': 0 # Assign 0 for 'Unknown' severity if it exists
    }
    # Apply mapping. Use .fillna(0) in case 'Unknown' or other unexpected values appear later.
    df['severity_encoded'] = df['severity'].map(severity_mapping).fillna(0).astype(int)
    print("Mapping for 'severity':")
    for key, value in severity_mapping.items():
        print(f"  {key} -> {value}")
    df.drop(columns=['severity'], inplace=True)
else:
    print("'severity' column not found, skipping encoding.")

Mapping for 'severity':
  Critical -> 4
  Major -> 3
  Minor -> 2
  Warning -> 1
  Unknown -> 0

#### 3. `occurred_on` -> Extract temporal features

In [89]:
if 'occurred_on' in df.columns:
    df['occurred_on_hour'] = df['occurred_on'].dt.hour
    df['occurred_on_day'] = df['occurred_on'].dt.day
    df['occurred_on_weekday'] = df['occurred_on'].dt.weekday # Monday=0, Sunday=6
    df['occurred_on_month'] = df['occurred_on'].dt.month
    df.drop(columns=['occurred_on'], inplace=True)
    print("Extracted hour, day, weekday, month from 'occurred_on'.")
else:
    print("'occurred_on' column not found, skipping feature extraction.")

Extracted hour, day, weekday, month from 'occurred_on'.

#### 5. `alarm_id` -> Keep as integer (no encoding)

In [90]:
if 'alarm_id' in df.columns:
    print("'alarm_id' kept as integer (no encoding). Current Dtype: ", df['alarm_id'].dtype)
else:
    print("'alarm_id' column not found.")

'alarm_id' kept as integer (no encoding). Current Dtype:  int32

#### 6. `mo_name` -> Label Encoding

In [91]:
if 'mo_name' in df.columns:
    le_mo_name = LabelEncoder()
    df['mo_name_encoded'] = le_mo_name.fit_transform(df['mo_name'])
    label_encoders['mo_name'] = le_mo_name
    print(f"Mapping for 'mo_name':")
    # Print only a subset of mappings if there are too many unique values
    if len(le_mo_name.classes_) > 20:
        print("  (Showing first 10 and last 10 unique values)")
        for i, item in enumerate(le_mo_name.classes_[:10]):
            print(f"  {item} -> {i}")
        print("  ...")
        for i, item in enumerate(le_mo_name.classes_[-10:]):
            print(f"  {item} -> {len(le_mo_name.classes_) - 10 + i}")
    else:
        for i, item in enumerate(le_mo_name.classes_):
            print(f"  {item} -> {i}")
    df.drop(columns=['mo_name'], inplace=True)
else:
    print("'mo_name' column not found, skipping encoding.")

Mapping for 'mo_name':
  (Showing first 10 and last 10 unique values)
  ACT_ENS -> 0
  AMADD1_GUL00_Addalachchnei_Am -> 1
  AMADD1_G_Addalaichenai__9__Am -> 2
  AMADD2_G0L00_Addalachchanai 2_IP_Am -> 3
  AMAKK1_GUL00_Akkareipattu_Am -> 4
  AMAKK1_G_AKKARAIPATTU__8_Xam -> 5
  AMAKK3_G0L00_Akkaraipattu_3_IP_Am -> 6
  AMAKK3_G_Akkereipattu__9__Am -> 7
  AMAMB1_G0L00_Ambalam_Oya_Am -> 8
  AMAMB1_G_AMBALAM_OYA1__9__Am -> 9
  ...
  gNodeB Function Name=RTRAT3_N_Kotugodella_Street_2_Ra -> 24275
  gNodeB Function Name=RTRAT6_Ratnapura_SLT_Ra -> 24276
  gNodeB Function Name=T5GKB1_0000N_Kurunegala Branch 5G_Ku -> 24277
  gNodeB Function Name=T5GWC1_N_World_Trade_Cente -> 24278
  gNodeB Function Name=ZMAH29_0000N_Mattegoda_North_Ho -> 24279
  gNodeB Function Name=ZMRT21_N_University_of_Moratuwa_De -> 24280
  gb -> 24281
  link -> 24282
  omo -> 24283
  usn -> 24284

#### 7. `alarm_name` -> Label Encoding

In [92]:
if 'alarm_name' in df.columns:
    le_alarm_name = LabelEncoder()
    df['alarm_name_encoded'] = le_alarm_name.fit_transform(df['alarm_name'])
    label_encoders['alarm_name'] = le_alarm_name
    print(f"Mapping for 'alarm_name':")
    if len(le_alarm_name.classes_) > 20:
        print("  (Showing first 10 and last 10 unique values)")
        for i, item in enumerate(le_alarm_name.classes_[:10]):
            print(f"  {item} -> {i}")
        print("  ...")
        for i, item in enumerate(le_alarm_name.classes_[-10:]):
            print(f"  {item} -> {len(le_alarm_name.classes_) - 10 + i}")
    else:
        for i, item in enumerate(le_alarm_name.classes_):
            print(f"  {item} -> {i}")
    df.drop(columns=['alarm_name'], inplace=True)
else:
    print("'alarm_name' column not found, skipping encoding.")

Mapping for 'alarm_name':
  (Showing first 10 and last 10 unique values)
  2G Cabinet Power Alarm -> 0
  2G MAX USERS -> 1
  4G USER count -> 2
  ABCF SIP(TCP) Dynamic Link Transmission Quality Degraded -> 3
  AC Input Power Failure -> 4
  AC Surge Protector Fault -> 5
  ALD Hardware Fault -> 6
  ALD Maintenance Link Failure -> 7
  ARP probe failure -> 8
  Abnormal Messages Received from the SCP -> 9
  ...
  User Plane Fault -> 470
  User Plane Path Fault -> 471
  Water Alarm -> 472
  X2 Interface Fault -> 473
  eNodeB Out of Service -> 474
  eNodeB S1 Control Plane Transmission Interruption -> 475
  gNodeB NG Interface Fault -> 476
  gNodeB Out of Service -> 477
  gNodeB X2 Interface Fault -> 478
  iGWB-ACM disconnected -> 479

#### 8. `location_information` -> Keep for now (do not encode)

In [93]:
if 'location_information' in df.columns:
    print("'location_information' column kept for now as requested.")
else:
    print("'location_information' column not found.")

'location_information' column kept for now as requested.

#### 9. `additional_information` -> Keep for now (do not encode)

In [94]:
if 'additional_information' in df.columns:
    print("'additional_information' column kept for now as requested.")
else:
    print("'additional_information' column not found.")

'additional_information' column kept for now as requested.

#### 10. `alarm_duration` -> Convert to numeric minutes

In [95]:
def convert_duration_to_minutes(duration_str):
    if pd.isna(duration_str) or duration_str == 'Unknown': # Handle NaN and 'Unknown' values
        return np.nan # Use np.nan for missing/unknown durations

    total_minutes = 0
    parts = duration_str.split(' ')
    i = 0
    while i < len(parts):
        try:
            value = int(parts[i])
            unit = parts[i+1].lower()
            if 'hour' in unit:
                total_minutes += value * 60
            elif 'minute' in unit:
                total_minutes += value
            elif 'second' in unit:
                total_minutes += value / 60
            i += 2
        except (ValueError, IndexError):
            i += 1 # Skip problematic parts
            continue
    return total_minutes

if 'alarm_duration' in df.columns:
    df['alarm_duration_minutes'] = df['alarm_duration'].apply(convert_duration_to_minutes)
    df.drop(columns=['alarm_duration'], inplace=True)
    print("'alarm_duration' converted to 'alarm_duration_minutes'.")
else:
    print("'alarm_duration' column not found, skipping conversion.")

'alarm_duration' converted to 'alarm_duration_minutes'.

#### 11. `alarm_source` -> Label Encoding

In [96]:
if 'alarm_source' in df.columns:
    le_alarm_source = LabelEncoder()
    df['alarm_source_encoded'] = le_alarm_source.fit_transform(df['alarm_source'])
    label_encoders['alarm_source'] = le_alarm_source
    print(f"Mapping for 'alarm_source':")
    if len(le_alarm_source.classes_) > 20:
        print("  (Showing first 10 and last 10 unique values)")
        for i, item in enumerate(le_alarm_source.classes_[:10]):
            print(f"  {item} -> {i}")
        print("  ...")
        for i, item in enumerate(le_alarm_source.classes_[-10:]):
            print(f"  {item} -> {len(le_alarm_source.classes_) - 10 + i}")
    else:
        for i, item in enumerate(le_alarm_source.classes_):
            print(f"  {item} -> {i}")
    df.drop(columns=['alarm_source'], inplace=True)
else:
    print("'alarm_source' column not found, skipping encoding.")

Mapping for 'alarm_source':
  (Showing first 10 and last 10 unique values)
  ACT_ENS -> 0
  AMADD1_GUL00_Addalachchnei_Am -> 1
  AMADD2_G0L00_Addalachchanai 2_IP_Am -> 2
  AMAKK1_GUL00_Akkareipattu_Am -> 3
  AMAKK3_G0L00_Akkaraipattu_3_IP_Am -> 4
  AMAMB1_G0L00_Ambalam_Oya_Am -> 5
  AMAMB2_G0L00_Ambalanoya2_Am -> 6
  AMAMP1_0UL00_Ampara_Am -> 7
  AMAMP2_0UL00_Ampara2_Am -> 8
  AMAMP3_0UL00_Ampara3_Am -> 9
  ...
  dc2_UDM_FE -> 5518
  dc3_CloudSE298001 -> 5519
  dc3_UDG_UPF01 -> 5520
  dc3_UDM_BE -> 5521
  dc3_UDM_FE -> 5522
  dc3_UNC_AMF01 -> 5523
  dc3_UNC_NCG01 -> 5524
  dc3_UNC_NRF01 -> 5525
  dc3_UNC_SMF01 -> 5526
  eSight01 -> 5527

#### 12. `maintenance_status` -> Label Encoding

In [97]:
if 'maintenance_status' in df.columns:
    le_maintenance_status = LabelEncoder()
    df['maintenance_status_encoded'] = le_maintenance_status.fit_transform(df['maintenance_status'])
    label_encoders['maintenance_status'] = le_maintenance_status
    print(f"Mapping for 'maintenance_status':")
    for i, item in enumerate(le_maintenance_status.classes_):
        print(f"  {item} -> {i}")
    df.drop(columns=['maintenance_status'], inplace=True)
else:
    print("'maintenance_status' column not found, skipping encoding.")

Mapping for 'maintenance_status':
  NORMAL -> 0

#### 14. `ne_type` -> Label Encoding

In [98]:
if 'ne_type' in df.columns:
    le_ne_type = LabelEncoder()
    df['ne_type_encoded'] = le_ne_type.fit_transform(df['ne_type'])
    label_encoders['ne_type'] = le_ne_type
    print(f"Mapping for 'ne_type':")
    for i, item in enumerate(le_ne_type.classes_):
        print(f"  {item} -> {i}")
    df.drop(columns=['ne_type'], inplace=True)
else:
    print("'ne_type' column not found, skipping encoding.")

Mapping for 'ne_type':
  ATS -> 0
  BSC6910 GU -> 1
  BTS3900 -> 2
  BTS3900 LTE -> 3
  BTS3900 WCDMA -> 4
  BTS3902E WCDMA -> 5
  BTS5900 -> 6
  CCF -> 7
  CG -> 8
  CGPOMU -> 9
  CSCF -> 10
  CSP -> 11
  CloudSE2980 -> 12
  CloudUDN -> 13
  DBS3900 IBS -> 14
  ENS -> 15
  FusionStage -> 16
  GBTS -> 17
  MGW -> 18
  MICRO BTS3900 -> 19
  MRFP -> 20
  MSCServer -> 21
  OSS -> 22
  PICO BTS3900 -> 23
  SAE-HSS -> 24
  SE2900 -> 25
  SG7000 -> 26
  SPG -> 27
  SPSV3 -> 28
  UDG -> 29
  UDM -> 30
  UGW -> 31
  UIM -> 32
  UNC -> 33
  UPCC -> 34
  USCDB -> 35
  USN -> 36
  eSight-NFV -> 37
  vCG -> 38
  vUGW -> 39
  vUSN -> 40

#### 15. `object_type` -> Label Encoding

In [99]:
if 'object_type' in df.columns:
    le_object_type = LabelEncoder()
    df['object_type_encoded'] = le_object_type.fit_transform(df['object_type'])
    label_encoders['object_type'] = le_object_type
    print(f"Mapping for 'object_type':")
    for i, item in enumerate(le_object_type.classes_):
        print(f"  {item} -> {i}")
    df.drop(columns=['object_type'], inplace=True)
else:
    print("'object_type' column not found, skipping encoding.")

Mapping for 'object_type':
  BSC6910 GU -> 0
  BTS -> 1
  BTS3900 -> 2
  Board -> 3
  CGW_VNFC -> 4
  CG_VNFC -> 5
  Cell -> 6
  DGW_VNFC -> 7
  EthernetInterface -> 8
  GBTS Function -> 9
  GB_VNFC -> 10
  GNBCUNGInterface -> 11
  HLRFUNCTION -> 12
  HSSFUNCTION -> 13
  IPPMSESSION -> 14
  IPPath -> 15
  IkePeer -> 16
  IpClkServer -> 17
  IpOam -> 18
  IppmSession -> 19
  LINK_VNFC -> 20
  MGWSIGLink -> 21
  MSCServer -> 22
  NRCell -> 23
  NRDuCell -> 24
  NRDuCellTrp -> 25
  NodeB -> 26
  NodeB Function -> 27
  OMO_VNFC -> 28
  OSS -> 29
  RFAFunction -> 30
  RFALoCell -> 31
  RRU -> 32
  S1Interface -> 33
  SCTPLink -> 34
  SG7000 -> 35
  SctpAssociation -> 36
  Subrack -> 37
  SystemClock -> 38
  Time -> 39
  UGW -> 40
  USN -> 41
  USN_VNFC -> 42
  Unknown -> 43
  eNodeB Function -> 44
  gNodeB Function -> 45
  vUGW -> 46
  vUSN -> 47

#### 16. `received_on` -> Extract date features

In [122]:
if 'received_on' in df.columns:
    df['received_on_hour'] = df['received_on'].dt.hour
    df['received_on_day'] = df['received_on'].dt.day
    df['received_on_weekday'] = df['received_on'].dt.weekday
    df['received_on_month'] = df['received_on'].dt.month
    # df.drop(columns=['received_on'], inplace=True) # Removed as per user request to keep the datetime column
    print("Extracted hour, day, weekday, month from 'received_on'.")
else:
    print("'received_on' column not found, skipping feature extraction.")

'received_on' column not found, skipping feature extraction.

#### 17. `subnet` -> Label Encoding

In [101]:
if 'subnet' in df.columns:
    le_subnet = LabelEncoder()
    df['subnet_encoded'] = le_subnet.fit_transform(df['subnet'])
    label_encoders['subnet'] = le_subnet
    print(f"Mapping for 'subnet':")
    if len(le_subnet.classes_) > 20:
        print("  (Showing first 10 and last 10 unique values)")
        for i, item in enumerate(le_subnet.classes_[:10]):
            print(f"  {item} -> {i}")
        print("  ...")
        for i, item in enumerate(le_subnet.classes_[-10:]):
            print(f"  {item} -> {len(le_subnet.classes_) - 10 + i}")
    else:
        for i, item in enumerate(le_subnet.classes_):
            print(f"  {item} -> {i}")
    df.drop(columns=['subnet'], inplace=True)
else:
    print("'subnet' column not found, skipping encoding.")

Mapping for 'subnet':
  (Showing first 10 and last 10 unique values)
  ROOT -> 0
  ROOT/AutoDiscoverSRAN -> 1
  ROOT/CN Subnet -> 2
  ROOT/CN Subnet/VOLTE -> 3
  ROOT/Cloud ILayer Subnet -> 4
  ROOT/EASY_DEPLOYMENT -> 5
  ROOT/PS Core Subnet -> 6
  ROOT/RAN Subnet/BTS -> 7
  ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT -> 8
  ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GL -> 9
  ...
  ROOT/RAN Subnet/BTS/Single DAS -> 24
  ROOT/RAN Subnet/BTS/eGBTS -> 25
  ROOT/RAN Subnet/LTE/L1800 -> 26
  ROOT/RAN Subnet/LTE/L900 -> 27
  ROOT/RAN Subnet/MBSC -> 28
  ROOT/RAN Subnet/MBSC/MBSC35 -> 29
  ROOT/RAN Subnet/MBSC/MBSC36 -> 30
  ROOT/RAN Subnet/MBSC/MBSC37 -> 31
  ROOT/RAN Subnet/Test Nodes/MBTS -> 32
  ROOT/RAN Subnet/Test Nodes/RNC -> 33

#### 18. `type` -> Label Encoding

In [102]:
if 'type' in df.columns:
    le_type = LabelEncoder()
    df['type_encoded'] = le_type.fit_transform(df['type'])
    label_encoders['type'] = le_type
    print(f"Mapping for 'type':")
    for i, item in enumerate(le_type.classes_):
        print(f"  {item} -> {i}")
    df.drop(columns=['type'], inplace=True)
else:
    print("'type' column not found, skipping encoding.")

Mapping for 'type':
  Communication system -> 0
  Environment system -> 1
  Hardware system -> 2
  Internal -> 3
  Operational violation -> 4
  Power system -> 5
  Processing error -> 6
  QoS -> 7
  Running system -> 8
  Security service or mechanism violation -> 9
  Signaling system -> 10
  Software system -> 11
  Trunk system -> 12

#### 19. `enodeb_id` -> Do NOT encode (for grouping only)

In [103]:
if 'enodeb_id' in df.columns:
    print("'enodeb_id' column kept as is for grouping purposes.")
else:
    print("'enodeb_id' column not found.")

'enodeb_id' column kept as is for grouping purposes.

#### 20. `gnodeb_id` -> Keep separately for future 5G analysis

In [104]:
if 'gnodeb_id' in df.columns:
    print("'gnodeb_id' column kept separately for future 5G analysis.")
else:
    print("'gnodeb_id' column not found.")

'gnodeb_id' column kept separately for future 5G analysis.

### Encoding Summary

All specified encoding steps have been applied. The `label_encoders` dictionary contains the fitted `LabelEncoder` objects for all label-encoded columns. The DataFrame `df` now contains the newly engineered features and encoded columns. Let's inspect the final DataFrame structure.

In [105]:
print("\nDataFrame info after all encoding steps:")
display(df.info())
display(df.head())

DataFrame info after all encoding steps:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 1 to 999999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   alarm_id                    999999 non-null  int32
 1   location_information        999999 non-null  category
 2   additional_information      999999 non-null  category
 3   enodeb_id                   999999 non-null  category
 4   gnodeb_id                   999999 non-null  category
 5   alarm_type_encoded          999999 non-null  int64
 6   severity_encoded            999999 non-null  int64
 7   occurred_on_hour            999999 non-null  int32
 8   occurred_on_day             999999 non-null  int32
 9   occurred_on_weekday         999999 non-null  int32
 10  occurred_on_month           999999 non-null  int32
 11  mo_name_encoded             999999 non-null  int64
 12  alarm_name_encoded          999999 non-null  int64
 13  alarm_duration_minutes      999999 non-null  float64
 14  alarm_source_encoded        999999 non-null  int64
 15  maintenance_status_encoded  999999 non-null  int64
 16  ne_type_encoded             999999 non-null  int64
 17  object_type_encoded         999999 non-null  int64
 18  received_on_hour            999999 non-null  int32
 19  received_on_day             999999 non-null  int32
 20  received_on_weekday         999999 non-null  int32
 21  received_on_month           999999 non-null  int32
 22  subnet_encoded              999999 non-null  int64
 23  type_encoded                999999 non-null  int64
dtypes: category(4), float64(1), int32(9), int64(10)
memory usage: 141.0 MB

None

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,alarm_source_encoded,maintenance_status_encoded,ne_type_encoded,object_type_encoded,received_on_hour,received_on_day,received_on_weekday,received_on_month,subnet_encoded,type_encoded
1,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10
2,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10
3,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10
4,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10
5,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",3537,Unknown,4,4,19,7,1,...,144,0,2,6,19,7,1,7,12,10

### Handling Outliers

tradition outliers handling is not done. too much data sensitivity

### Feature Engineering

Based on the project objectives, we will now engineer sequence-based features per tower (`enodeb_id`). Each tower's alarms will be processed independently and chronologically. The `WINDOW_SIZE` parameter will control how many previous alarms are considered for certain features.

In [108]:
# Define the window size for previous alarms
WINDOW_SIZE = 5

print(f"Feature engineering will use a window size of: {WINDOW_SIZE}")

Feature engineering will use a window size of: 5

First, we must ensure the DataFrame is sorted by `enodeb_id` and then chronologically by the `occurred_on` attributes (hour, day, weekday, month) for correct sequence-based feature generation. Since the original `occurred_on` datetime column was dropped, we will sort using the extracted temporal features, acknowledging this might not be perfectly precise down to the second/minute.

In [109]:
# Sort the DataFrame by enodeb_id and then by occurred_on's temporal features
df.sort_values(by=['enodeb_id', 'occurred_on_month', 'occurred_on_day', 'occurred_on_hour', 'occurred_on_weekday'], inplace=True)
print("DataFrame sorted by 'enodeb_id' and 'occurred_on' temporal features.")
display(df.head())

DataFrame sorted by 'enodeb_id' and 'occurred_on' temporal features.

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,alarm_source_encoded,maintenance_status_encoded,ne_type_encoded,object_type_encoded,received_on_hour,received_on_day,received_on_weekday,received_on_month,subnet_encoded,type_encoded
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,1316,0,2,34,7,1,2,7,14,12
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,1316,0,2,34,7,1,2,7,14,12
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,1316,0,2,34,12,1,2,7,14,12
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,1316,0,2,43,18,1,2,7,14,1
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,1316,0,2,34,21,1,2,7,14,12

#### 1. Previous Alarm Features (`previous_alarm_N`)

We will create features indicating the `alarm_name_encoded` of the `N` most recent previous alarms for each tower. A value of -1 will indicate no previous alarm.

In [110]:
# Generate previous_alarm_N features
for i in range(1, WINDOW_SIZE + 1):
    df[f'previous_alarm_{i}'] = df.groupby('enodeb_id')['alarm_name_encoded'].shift(i).fillna(-1).astype(int)
print(f"Generated 'previous_alarm_1' to 'previous_alarm_{WINDOW_SIZE}' features.")
display(df.head())

/tmp/ipykernel_721/424932680.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_{i}'] = df.groupby('enodeb_id')['alarm_name_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/424932680.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_{i}'] = df.groupby('enodeb_id')['alarm_name_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/424932680.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_{i}'] = df.groupby('enodeb_id')['alarm_name_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/424932680.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_{i}'] = df.groupby('enodeb_id')['alarm_name_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/424932680.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_{i}'] = df.groupby('enodeb_id')['alarm_name_encoded'].shift(i).fillna(-1).astype(int)

Generated 'previous_alarm_1' to 'previous_alarm_5' features.

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,received_on_day,received_on_weekday,received_on_month,subnet_encoded,type_encoded,previous_alarm_1,previous_alarm_2,previous_alarm_3,previous_alarm_4,previous_alarm_5
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,1,2,7,14,12,-1,-1,-1,-1,-1
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,1,2,7,14,12,379,-1,-1,-1,-1
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,1,2,7,14,12,379,379,-1,-1,-1
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,1,2,7,14,1,379,379,379,-1,-1
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,1,2,7,14,12,161,379,379,379,-1

#### 2. Previous Severity Features (`previous_severity_N`)

Similarly, we create features for the `severity_encoded` of the `N` most recent previous alarms for each tower.

In [111]:
# Generate previous_severity_N features
for i in range(1, WINDOW_SIZE + 1):
    df[f'previous_severity_{i}'] = df.groupby('enodeb_id')['severity_encoded'].shift(i).fillna(-1).astype(int)
print(f"Generated 'previous_severity_1' to 'previous_severity_{WINDOW_SIZE}' features.")
display(df.head())

/tmp/ipykernel_721/418543919.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_severity_{i}'] = df.groupby('enodeb_id')['severity_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/418543919.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_severity_{i}'] = df.groupby('enodeb_id')['severity_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/418543919.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_severity_{i}'] = df.groupby('enodeb_id')['severity_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/418543919.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_severity_{i}'] = df.groupby('enodeb_id')['severity_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/418543919.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_severity_{i}'] = df.groupby('enodeb_id')['severity_encoded'].shift(i).fillna(-1).astype(int)

Generated 'previous_severity_1' to 'previous_severity_5' features.

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_alarm_1,previous_alarm_2,previous_alarm_3,previous_alarm_4,previous_alarm_5,previous_severity_1,previous_severity_2,previous_severity_3,previous_severity_4,previous_severity_5
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,379,-1,-1,-1,-1,3,-1,-1,-1,-1
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,379,379,-1,-1,-1,3,3,-1,-1,-1
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,379,379,379,-1,-1,3,3,3,-1,-1
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,161,379,379,379,-1,3,3,3,3,-1

#### 3. Previous Alarm Source Features (`previous_alarm_source_N`)

Generating features for the `alarm_source_encoded` of the `N` most recent previous alarms.

In [112]:
# Generate previous_alarm_source_N features
for i in range(1, WINDOW_SIZE + 1):
    df[f'previous_alarm_source_{i}'] = df.groupby('enodeb_id')['alarm_source_encoded'].shift(i).fillna(-1).astype(int)
print(f"Generated 'previous_alarm_source_1' to 'previous_alarm_source_{WINDOW_SIZE}' features.")
display(df.head())

Generated 'previous_alarm_source_1' to 'previous_alarm_source_5' features.

/tmp/ipykernel_721/2630975019.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_source_{i}'] = df.groupby('enodeb_id')['alarm_source_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/2630975019.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_source_{i}'] = df.groupby('enodeb_id')['alarm_source_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/2630975019.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_source_{i}'] = df.groupby('enodeb_id')['alarm_source_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/2630975019.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_source_{i}'] = df.groupby('enodeb_id')['alarm_source_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/2630975019.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_source_{i}'] = df.groupby('enodeb_id')['alarm_source_encoded'].shift(i).fillna(-1).astype(int)

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_severity_1,previous_severity_2,previous_severity_3,previous_severity_4,previous_severity_5,previous_alarm_source_1,previous_alarm_source_2,previous_alarm_source_3,previous_alarm_source_4,previous_alarm_source_5
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,3,-1,-1,-1,-1,1316,-1,-1,-1,-1
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,3,3,-1,-1,-1,1316,1316,-1,-1,-1
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,3,3,3,-1,-1,1316,1316,1316,-1,-1
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,3,3,3,3,-1,1316,1316,1316,1316,-1

#### 4. Previous Object Type Features (`previous_object_type_N`)

Generating features for the `object_type_encoded` of the `N` most recent previous alarms.

In [113]:
# Generate previous_object_type_N features
for i in range(1, WINDOW_SIZE + 1):
    df[f'previous_object_type_{i}'] = df.groupby('enodeb_id')['object_type_encoded'].shift(i).fillna(-1).astype(int)
print(f"Generated 'previous_object_type_1' to 'previous_object_type_{WINDOW_SIZE}' features.")
display(df.head())

/tmp/ipykernel_721/4217811492.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_object_type_{i}'] = df.groupby('enodeb_id')['object_type_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/4217811492.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_object_type_{i}'] = df.groupby('enodeb_id')['object_type_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/4217811492.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_object_type_{i}'] = df.groupby('enodeb_id')['object_type_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/4217811492.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_object_type_{i}'] = df.groupby('enodeb_id')['object_type_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/4217811492.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_object_type_{i}'] = df.groupby('enodeb_id')['object_type_encoded'].shift(i).fillna(-1).astype(int)

Generated 'previous_object_type_1' to 'previous_object_type_5' features.

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_alarm_source_1,previous_alarm_source_2,previous_alarm_source_3,previous_alarm_source_4,previous_alarm_source_5,previous_object_type_1,previous_object_type_2,previous_object_type_3,previous_object_type_4,previous_object_type_5
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,1316,-1,-1,-1,-1,34,-1,-1,-1,-1
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,1316,1316,-1,-1,-1,34,34,-1,-1,-1
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,1316,1316,1316,-1,-1,34,34,34,-1,-1
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,1316,1316,1316,1316,-1,43,34,34,34,-1

#### 5. Previous Alarm Type Features (`previous_alarm_type_N`)

Generating features for the `alarm_type_encoded` of the `N` most recent previous alarms.

In [114]:
# Generate previous_alarm_type_N features
for i in range(1, WINDOW_SIZE + 1):
    df[f'previous_alarm_type_{i}'] = df.groupby('enodeb_id')['alarm_type_encoded'].shift(i).fillna(-1).astype(int)
print(f"Generated 'previous_alarm_type_1' to 'previous_alarm_type_{WINDOW_SIZE}' features.")
display(df.head())

/tmp/ipykernel_721/581094104.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_type_{i}'] = df.groupby('enodeb_id')['alarm_type_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/581094104.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_type_{i}'] = df.groupby('enodeb_id')['alarm_type_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/581094104.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_type_{i}'] = df.groupby('enodeb_id')['alarm_type_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/581094104.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_type_{i}'] = df.groupby('enodeb_id')['alarm_type_encoded'].shift(i).fillna(-1).astype(int)
/tmp/ipykernel_721/581094104.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f'previous_alarm_type_{i}'] = df.groupby('enodeb_id')['alarm_type_encoded'].shift(i).fillna(-1).astype(int)

Generated 'previous_alarm_type_1' to 'previous_alarm_type_5' features.

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_object_type_1,previous_object_type_2,previous_object_type_3,previous_object_type_4,previous_object_type_5,previous_alarm_type_1,previous_alarm_type_2,previous_alarm_type_3,previous_alarm_type_4,previous_alarm_type_5
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,34,-1,-1,-1,-1,4,-1,-1,-1,-1
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,34,34,-1,-1,-1,4,4,-1,-1,-1
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,34,34,34,-1,-1,4,4,4,-1,-1
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,43,34,34,34,-1,8,4,4,4,-1

#### 6. Time Gap Feature (`time_gap_previous_alarm`)

This feature calculates the time difference between the current alarm and the immediately preceding alarm within the same tower. **As noted previously, the original `occurred_on` datetime column is no longer available in the DataFrame. Therefore, this feature cannot be calculated accurately as a precise time difference. We will create a placeholder column for now.**

In [115]:
# Placeholder for time_gap_previous_alarm
# This feature cannot be accurately calculated as a precise time difference
# because the original 'occurred_on' datetime column was dropped.
# If precise time gaps are required, the data loading/preprocessing needs to be revisited.

df['time_gap_previous_alarm'] = np.nan
print("Placeholder 'time_gap_previous_alarm' column created due to missing 'occurred_on' datetime column.")
display(df.head())

Placeholder 'time_gap_previous_alarm' column created due to missing 'occurred_on' datetime column.

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_object_type_2,previous_object_type_3,previous_object_type_4,previous_object_type_5,previous_alarm_type_1,previous_alarm_type_2,previous_alarm_type_3,previous_alarm_type_4,previous_alarm_type_5,time_gap_previous_alarm
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,NaN
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,4,-1,-1,-1,-1,NaN
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,34,-1,-1,-1,4,4,-1,-1,-1,NaN
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,34,34,-1,-1,4,4,4,-1,-1,NaN
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,34,34,34,-1,8,4,4,4,-1,NaN

#### 7. Sequence Length (`sequence_length`)

This feature indicates the number of alarms that have occurred for a specific tower *before* the current alarm.

In [116]:
# Calculate sequence_length (number of alarms before the current one)
df['sequence_length'] = df.groupby('enodeb_id').cumcount()
print("Generated 'sequence_length' feature.")
display(df.head())

Generated 'sequence_length' feature.

/tmp/ipykernel_721/3752698005.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['sequence_length'] = df.groupby('enodeb_id').cumcount()

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_object_type_3,previous_object_type_4,previous_object_type_5,previous_alarm_type_1,previous_alarm_type_2,previous_alarm_type_3,previous_alarm_type_4,previous_alarm_type_5,time_gap_previous_alarm,sequence_length
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,-1,-1,-1,NaN,0
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,4,-1,-1,-1,-1,NaN,1
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,-1,-1,-1,4,4,-1,-1,-1,NaN,2
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,34,-1,-1,4,4,4,-1,-1,NaN,3
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,34,34,-1,8,4,4,4,-1,NaN,4

#### 8. Alarm Repeat Count (`alarm_repeat_count`)

This feature counts how many times the *current* alarm (`alarm_name_encoded`) has previously occurred within the same tower's history.

In [117]:
# Calculate alarm_repeat_count
# This counts how many times the current alarm has previously appeared in the sequence for that enodeb_id
df['alarm_repeat_count'] = df.groupby(['enodeb_id', 'alarm_name_encoded']).cumcount()
print("Generated 'alarm_repeat_count' feature.")
display(df.head())

Generated 'alarm_repeat_count' feature.

/tmp/ipykernel_721/4268462942.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['alarm_repeat_count'] = df.groupby(['enodeb_id', 'alarm_name_encoded']).cumcount()

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_object_type_4,previous_object_type_5,previous_alarm_type_1,previous_alarm_type_2,previous_alarm_type_3,previous_alarm_type_4,previous_alarm_type_5,time_gap_previous_alarm,sequence_length,alarm_repeat_count
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,-1,-1,NaN,0,0
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,4,-1,-1,-1,-1,NaN,1,1
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,-1,-1,4,4,-1,-1,-1,NaN,2,2
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,-1,-1,4,4,4,-1,-1,NaN,3,0
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,34,-1,8,4,4,4,-1,NaN,4,3

#### 9. Previous Cell Unavailable Count (`previous_cell_unavailable_count`)

This feature counts how many 'Cell Unavailable' alarms have occurred previously for a given tower.

In [118]:
# Get the encoded value for 'Cell Unavailable'
cell_unavailable_encoded_value = label_encoders['alarm_name'].transform(['Cell Unavailable'])[0]

# Create a boolean series for 'Cell Unavailable' alarms
df['is_cell_unavailable'] = (df['alarm_name_encoded'] == cell_unavailable_encoded_value).astype(int)

# Calculate previous_cell_unavailable_count
# Use cumsum() and then shift(1) to get the count *before* the current alarm
df['previous_cell_unavailable_count'] = df.groupby('enodeb_id')['is_cell_unavailable'].cumsum().shift(1).fillna(0).astype(int)

# Drop the intermediate 'is_cell_unavailable' column
df.drop(columns=['is_cell_unavailable'], inplace=True)

print("Generated 'previous_cell_unavailable_count' feature.")
display(df.head())

/tmp/ipykernel_721/1176201442.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['previous_cell_unavailable_count'] = df.groupby('enodeb_id')['is_cell_unavailable'].cumsum().shift(1).fillna(0).astype(int)

Generated 'previous_cell_unavailable_count' feature.

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_object_type_5,previous_alarm_type_1,previous_alarm_type_2,previous_alarm_type_3,previous_alarm_type_4,previous_alarm_type_5,time_gap_previous_alarm,sequence_length,alarm_repeat_count,previous_cell_unavailable_count
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,-1,NaN,0,0,0
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,4,-1,-1,-1,-1,NaN,1,1,0
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,-1,4,4,-1,-1,-1,NaN,2,2,0
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,-1,4,4,4,-1,-1,NaN,3,0,0
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,-1,8,4,4,4,-1,NaN,4,3,0

### Target Variable Creation

We will create a binary target variable (`target`) indicating whether a 'Cell Unavailable' event occurs *after* the current alarm within the same tower's sequence.

In [119]:
# Recreate 'is_cell_unavailable' for target creation
cell_unavailable_encoded_value = label_encoders['alarm_name'].transform(['Cell Unavailable'])[0]
df['is_cell_unavailable_for_target'] = (df['alarm_name_encoded'] == cell_unavailable_encoded_value).astype(int)

# Calculate the target: 1 if a 'Cell Unavailable' occurs AFTER the current alarm in the same tower sequence, else 0
# We use a reverse cumulative max, then reverse back, and shift to ensure it's a *future* event.
df['target'] = df.groupby('enodeb_id')['is_cell_unavailable_for_target'].transform(
    lambda x: x.iloc[::-1].cummax().iloc[::-1].shift(1).fillna(0)
).astype(int)

# Drop the intermediate column
df.drop(columns=['is_cell_unavailable_for_target'], inplace=True)

print("Generated 'target' variable.")
display(df.head())

/tmp/ipykernel_721/1257816530.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['target'] = df.groupby('enodeb_id')['is_cell_unavailable_for_target'].transform(

Generated 'target' variable.

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_alarm_type_1,previous_alarm_type_2,previous_alarm_type_3,previous_alarm_type_4,previous_alarm_type_5,time_gap_previous_alarm,sequence_length,alarm_repeat_count,previous_cell_unavailable_count,target
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,NaN,0,0,0,0
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,4,-1,-1,-1,-1,NaN,1,1,0,0
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,4,4,-1,-1,-1,NaN,2,2,0,0
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,4,4,4,-1,-1,NaN,3,0,0,0
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,8,4,4,4,-1,NaN,4,3,0,0

### Final DataFrame Structure

All specified features and the target variable have been created. Let's inspect the final DataFrame information and a sample of the data.

In [120]:
print("\nDataFrame info after feature engineering:")
display(df.info())
print("\nFirst 5 rows of the DataFrame with new features:")
display(df.head())

print("\nDescription of newly created features:")
new_features = [
    f'previous_alarm_{i}' for i in range(1, WINDOW_SIZE + 1)
] + [
    f'previous_severity_{i}' for i in range(1, WINDOW_SIZE + 1)
] + [
    f'previous_alarm_source_{i}' for i in range(1, WINDOW_SIZE + 1)
] + [
    f'previous_object_type_{i}' for i in range(1, WINDOW_SIZE + 1)
] + [
    f'previous_alarm_type_{i}' for i in range(1, WINDOW_SIZE + 1)
] + [
    'time_gap_previous_alarm', 'sequence_length', 'alarm_repeat_count',
    'previous_cell_unavailable_count', 'target'
]

for feature in new_features:
    if feature in df.columns:
        print(f"- {feature}: {df[feature].dtype} - A brief description of this feature.")
    else:
        print(f"- {feature}: Not found in DataFrame. (Likely time_gap_previous_alarm)")

DataFrame info after feature engineering:
<class 'pandas.core.frame.DataFrame'>
Index: 999999 entries, 205910 to 199998
Data columns (total 54 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   alarm_id                         999999 non-null  int32
 1   location_information             999999 non-null  category
 2   additional_information           999999 non-null  category
 3   enodeb_id                        999999 non-null  category
 4   gnodeb_id                        999999 non-null  category
 5   alarm_type_encoded               999999 non-null  int8
 6   severity_encoded                 999999 non-null  int8
 7   occurred_on_hour                 999999 non-null  int8
 8   occurred_on_day                  999999 non-null  int8
 9   occurred_on_weekday              999999 non-null  int8
 10  occurred_on_month                999999 non-null  int8
 11  mo_name_encoded                  999999 non-null  int16
 12  alarm_name_encoded               999999 non-null  int16
 13  alarm_duration_minutes           999999 non-null  float64
 14  alarm_source_encoded             999999 non-null  int16
 15  maintenance_status_encoded       999999 non-null  int8
 16  ne_type_encoded                  999999 non-null  int8
 17  object_type_encoded              999999 non-null  int8
 18  received_on_hour                 999999 non-null  int8
 19  received_on_day                  999999 non-null  int8
 20  received_on_weekday              999999 non-null  int8
 21  received_on_month                999999 non-null  int8
 22  subnet_encoded                   999999 non-null  int8
 23  type_encoded                     999999 non-null  int8
 24  previous_alarm_1                 999999 non-null  int64
 25  previous_alarm_2                 999999 non-null  int64
 26  previous_alarm_3                 999999 non-null  int64
 27  previous_alarm_4                 999999 non-null  int64
 28  previous_alarm_5                 999999 non-null  int64
 29  previous_severity_1              999999 non-null  int64
 30  previous_severity_2              999999 non-null  int64
 31  previous_severity_3              999999 non-null  int64
 32  previous_severity_4              999999 non-null  int64
 33  previous_severity_5              999999 non-null  int64
 34  previous_alarm_source_1          999999 non-null  int64
 35  previous_alarm_source_2          999999 non-null  int64
 36  previous_alarm_source_3          999999 non-null  int64
 37  previous_alarm_source_4          999999 non-null  int64
 38  previous_alarm_source_5          999999 non-null  int64
 39  previous_object_type_1           999999 non-null  int64
 40  previous_object_type_2           999999 non-null  int64
 41  previous_object_type_3           999999 non-null  int64
 42  previous_object_type_4           999999 non-null  int64
 43  previous_object_type_5           999999 non-null  int64
 44  previous_alarm_type_1            999999 non-null  int64
 45  previous_alarm_type_2            999999 non-null  int64
 46  previous_alarm_type_3            999999 non-null  int64
 47  previous_alarm_type_4            999999 non-null  int64
 48  previous_alarm_type_5            999999 non-null  int64
 49  time_gap_previous_alarm          0 non-null       float64
 50  sequence_length                  999999 non-null  int64
 51  alarm_repeat_count               999999 non-null  int64
 52  previous_cell_unavailable_count  999999 non-null  int64
 53  target                           999999 non-null  int64
dtypes: category(4), float64(2), int16(3), int32(1), int64(29), int8(15)
memory usage: 290.8 MB

None

First 5 rows of the DataFrame with new features:

,alarm_id,location_information,additional_information,enodeb_id,gnodeb_id,alarm_type_encoded,severity_encoded,occurred_on_hour,occurred_on_day,occurred_on_weekday,...,previous_alarm_type_1,previous_alarm_type_2,previous_alarm_type_3,previous_alarm_type_4,previous_alarm_type_5,time_gap_previous_alarm,sequence_length,alarm_repeat_count,previous_cell_unavailable_count,target
205910,25888,"Link No.=70306, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,-1,-1,-1,-1,-1,NaN,0,0,0,0
320681,25888,"Link No.=70180, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,7,1,2,...,4,-1,-1,-1,-1,NaN,1,1,0,0
212156,25888,"Link No.=70074, Description=eNodeB:MCC_413 MNC...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,12,1,2,...,4,4,-1,-1,-1,NaN,2,2,0,0
210419,65096,"Cabinet No.=0, Subrack No.=0, Slot No.=19, Por...","RAT_INFO=GUL, AFFECTED_RAT=GUL, DID=AUTODID_20...",0,Unknown,8,3,18,1,2,...,4,4,4,-1,-1,NaN,3,0,0,0
333693,25888,"Link No.=70182, Description=eNB:MCC_413 MNC_01...","RAT_INFO=GUL, AFFECTED_RAT=L, DID=AUTODID_2018...",0,Unknown,4,3,21,1,2,...,8,4,4,4,-1,NaN,4,3,0,0

Description of newly created features:
- previous_alarm_1: int64 - A brief description of this feature.
- previous_alarm_2: int64 - A brief description of this feature.
- previous_alarm_3: int64 - A brief description of this feature.
- previous_alarm_4: int64 - A brief description of this feature.
- previous_alarm_5: int64 - A brief description of this feature.
- previous_severity_1: int64 - A brief description of this feature.
- previous_severity_2: int64 - A brief description of this feature.
- previous_severity_3: int64 - A brief description of this feature.
- previous_severity_4: int64 - A brief description of this feature.
- previous_severity_5: int64 - A brief description of this feature.
- previous_alarm_source_1: int64 - A brief description of this feature.
- previous_alarm_source_2: int64 - A brief description of this feature.
- previous_alarm_source_3: int64 - A brief description of this feature.
- previous_alarm_source_4: int64 - A brief description of this feature.
- previous_alarm_source_5: int64 - A brief description of this feature.
- previous_object_type_1: int64 - A brief description of this feature.
- previous_object_type_2: int64 - A brief description of this feature.
- previous_object_type_3: int64 - A brief description of this feature.
- previous_object_type_4: int64 - A brief description of this feature.
- previous_object_type_5: int64 - A brief description of this feature.
- previous_alarm_type_1: int64 - A brief description of this feature.
- previous_alarm_type_2: int64 - A brief description of this feature.
- previous_alarm_type_3: int64 - A brief description of this feature.
- previous_alarm_type_4: int64 - A brief description of this feature.
- previous_alarm_type_5: int64 - A brief description of this feature.
- time_gap_previous_alarm: float64 - A brief description of this feature.
- sequence_length: int64 - A brief description of this feature.
- alarm_repeat_count: int64 - A brief description of this feature.
- previous_cell_unavailable_count: int64 - A brief description of this feature.
- target: int64 - A brief description of this feature.