In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

file_path = '/content/drive/MyDrive/MobitelData/mobi_data2_combined.csv'
df = pd.read_csv(file_path, low_memory=False)
display(df.head())

,,Severity,Occurred On (NT),Cleared On (NT),Alarm ID,MO Name,Comment,Name,Location Information,Additional Information,...,RRU Name,Received On (ST),Request ID,Subnet,Toggling Times,Trouble Ticket ID,Type,User Label,eNodeB ID,gNodeB ID
0,Root alarm,Critical,2026-07-07 19:24:39,2026-07-07 19:26:21,29240,"eNodeB Function Name=KLELU1_L_Eluwila_IP_Pi, L...",-,Cell Unavailable,"eNodeB Function Name=KLELU1_L_Eluwila_IP_Pi, L...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,4636,-
1,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:30,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
2,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:39,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
3,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-

In [4]:
new_column_names = [
    'alarm_type',
    'severity',
    'occurred_on',
    'cleared_on',
    'alarm_id',
    'mo_name',
    'comment',
    'alarm_name',
    'location_information',
    'additional_information',
    'alarm_duration',
    'alarm_source',
    'acknowledged_by',
    'acknowledged_on',
    'acknowledgement_status',
    'associated_alarm_group_id',
    'auto_clear',
    'bbu_name',
    'clearance_status',
    'clearance_type',
    'cleared_by',
    'common_alarm_identifier',
    'dev_root_csn',
    'equipment_alarm_serial_number',
    'external_resource_id',
    'link_name',
    'link_type',
    'log_serial_number',
    'maintenance_region',
    'maintenance_status',
    'ne_address',
    'ne_type',
    'object_type',
    'operation_impact_flag',
    'rru_name',
    'received_on',
    'request_id',
    'subnet',
    'toggling_times',
    'trouble_ticket_id',
    'type',
    'user_label',
    'enodeb_id',
    'gnodeb_id'
]

df.columns = new_column_names
display(df.head())

,alarm_type,severity,occurred_on,cleared_on,alarm_id,mo_name,comment,alarm_name,location_information,additional_information,...,rru_name,received_on,request_id,subnet,toggling_times,trouble_ticket_id,type,user_label,enodeb_id,gnodeb_id
0,,Severity,Occurred On (NT),Cleared On (NT),Alarm ID,MO Name,Comment,Name,Location Information,Additional Information,...,RRU Name,Received On (ST),Request ID,Subnet,Toggling Times,Trouble Ticket ID,Type,User Label,eNodeB ID,gNodeB ID
1,Root alarm,Critical,2026-07-07 19:24:39,2026-07-07 19:26:21,29240,"eNodeB Function Name=KLELU1_L_Eluwila_IP_Pi, L...",-,Cell Unavailable,"eNodeB Function Name=KLELU1_L_Eluwila_IP_Pi, L...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,4636,-
2,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:30,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
3,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:39,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-

In [6]:
df = df.iloc[1:].copy()
display(df.head())

,alarm_type,severity,occurred_on,cleared_on,alarm_id,mo_name,comment,alarm_name,location_information,additional_information,...,rru_name,received_on,request_id,subnet,toggling_times,trouble_ticket_id,type,user_label,enodeb_id,gnodeb_id
2,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:30,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
3,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:39,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
5,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
6,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-

Converting date time columns to datetimeobjects.

In [7]:
df['occurred_on'] = pd.to_datetime(df['occurred_on'], errors='coerce')
df['cleared_on'] = pd.to_datetime(df['cleared_on'], errors='coerce')

# Display the DataFrame info to verify the data types
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 2 to 1000000
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   alarm_type                     999999 non-null  object
 1   severity                       999999 non-null  object
 2   occurred_on                    999999 non-null  datetime64[ns]
 3   cleared_on                     999999 non-null  datetime64[ns]
 4   alarm_id                       999999 non-null  object
 5   mo_name                        999999 non-null  object
 6   comment                        999999 non-null  object
 7   alarm_name                     999999 non-null  object
 8   location_information           999999 non-null  object
 9   additional_information         999999 non-null  object
 10  alarm_duration                 999999 non-null  object
 11  alarm_source                   999999 non-null  object
 12  acknowledged_by                999999 non-null  object
 13  acknowledged_on                999999 non-null  object
 14  acknowledgement_status         999999 non-null  object
 15  associated_alarm_group_id      999999 non-null  object
 16  auto_clear                     999999 non-null  object
 17  bbu_name                       999999 non-null  object
 18  clearance_status               999999 non-null  object
 19  clearance_type                 999999 non-null  object
 20  cleared_by                     999999 non-null  object
 21  common_alarm_identifier        4092 non-null    object
 22  dev_root_csn                   999999 non-null  object
 23  equipment_alarm_serial_number  999999 non-null  object
 24  external_resource_id           999999 non-null  object
 25  link_name                      999999 non-null  object
 26  link_type                      999999 non-null  object
 27  log_serial_number              999999 non-null  object
 28  maintenance_region             999999 non-null  object
 29  maintenance_status             999999 non-null  object
 30  ne_address                     999999 non-null  object
 31  ne_type                        999999 non-null  object
 32  object_type                    999999 non-null  object
 33  operation_impact_flag          999999 non-null  object
 34  rru_name                       993266 non-null  object
 35  received_on                    999999 non-null  object
 36  request_id                     999999 non-null  object
 37  subnet                         999999 non-null  object
 38  toggling_times                 999999 non-null  object
 39  trouble_ticket_id              999999 non-null  object
 40  type                           999999 non-null  object
 41  user_label                     999999 non-null  object
 42  enodeb_id                      999999 non-null  object
 43  gnodeb_id                      999999 non-null  object
dtypes: datetime64[ns](2), object(42)
memory usage: 335.7+ MB

None

In [10]:
df['received_on'] = pd.to_datetime(df['received_on'], errors='coerce')
df['acknowledged_on'] = pd.to_datetime(df['acknowledged_on'], errors='coerce')

# Display the DataFrame info again to verify all datetime conversions
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 2 to 1000000
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   alarm_type                     999999 non-null  object
 1   severity                       999999 non-null  object
 2   occurred_on                    999999 non-null  datetime64[ns]
 3   cleared_on                     999999 non-null  datetime64[ns]
 4   alarm_id                       999999 non-null  object
 5   mo_name                        999999 non-null  object
 6   comment                        999999 non-null  object
 7   alarm_name                     999999 non-null  object
 8   location_information           999999 non-null  object
 9   additional_information         999999 non-null  object
 10  alarm_duration                 999999 non-null  object
 11  alarm_source                   999999 non-null  object
 12  acknowledged_by                999999 non-null  object
 13  acknowledged_on                999999 non-null  datetime64[ns]
 14  acknowledgement_status         999999 non-null  object
 15  associated_alarm_group_id      999999 non-null  object
 16  auto_clear                     999999 non-null  object
 17  bbu_name                       999999 non-null  object
 18  clearance_status               999999 non-null  object
 19  clearance_type                 999999 non-null  object
 20  cleared_by                     999999 non-null  object
 21  common_alarm_identifier        4092 non-null    object
 22  dev_root_csn                   999999 non-null  object
 23  equipment_alarm_serial_number  999999 non-null  object
 24  external_resource_id           999999 non-null  object
 25  link_name                      999999 non-null  object
 26  link_type                      999999 non-null  object
 27  log_serial_number              999999 non-null  object
 28  maintenance_region             999999 non-null  object
 29  maintenance_status             999999 non-null  object
 30  ne_address                     999999 non-null  object
 31  ne_type                        999999 non-null  object
 32  object_type                    999999 non-null  object
 33  operation_impact_flag          999999 non-null  object
 34  rru_name                       993266 non-null  object
 35  received_on                    999999 non-null  datetime64[ns]
 36  request_id                     999999 non-null  object
 37  subnet                         999999 non-null  object
 38  toggling_times                 999999 non-null  object
 39  trouble_ticket_id              999999 non-null  object
 40  type                           999999 non-null  object
 41  user_label                     999999 non-null  object
 42  enodeb_id                      999999 non-null  object
 43  gnodeb_id                      999999 non-null  object
dtypes: datetime64[ns](4), object(40)
memory usage: 335.7+ MB

None

Standardizing the column names

In [11]:
import re

def standardize_column_name(col_name):
    # Convert to lowercase
    col_name = col_name.lower()
    # Replace spaces with underscores
    col_name = col_name.replace(' ', '_')
    # Remove any characters that are not alphanumeric or underscores
    col_name = re.sub(r'[^a-z0-9_]', '', col_name)
    return col_name

df.columns = [standardize_column_name(col) for col in df.columns]

print("Standardized column names:")
display(df.columns.tolist())

Standardized column names:

['alarm_type',
 'severity',
 'occurred_on',
 'cleared_on',
 'alarm_id',
 'mo_name',
 'comment',
 'alarm_name',
 'location_information',
 'additional_information',
 'alarm_duration',
 'alarm_source',
 'acknowledged_by',
 'acknowledged_on',
 'acknowledgement_status',
 'associated_alarm_group_id',
 'auto_clear',
 'bbu_name',
 'clearance_status',
 'clearance_type',
 'cleared_by',
 'common_alarm_identifier',
 'dev_root_csn',
 'equipment_alarm_serial_number',
 'external_resource_id',
 'link_name',
 'link_type',
 'log_serial_number',
 'maintenance_region',
 'maintenance_status',
 'ne_address',
 'ne_type',
 'object_type',
 'operation_impact_flag',
 'rru_name',
 'received_on',
 'request_id',
 'subnet',
 'toggling_times',
 'trouble_ticket_id',
 'type',
 'user_label',
 'enodeb_id',
 'gnodeb_id']

Data Cleaning

Duplication checking and removing - no duplications are found

In [12]:
initial_rows = df.shape[0]
df.drop_duplicates(inplace=True)
duplicates_removed = initial_rows - df.shape[0]

print(f"Number of duplicate rows removed: {duplicates_removed}")
print(f"New DataFrame shape: {df.shape}")
display(df.head())

Number of duplicate rows removed: 0
New DataFrame shape: (999999, 44)

,alarm_type,severity,occurred_on,cleared_on,alarm_id,mo_name,comment,alarm_name,location_information,additional_information,...,rru_name,received_on,request_id,subnet,toggling_times,trouble_ticket_id,type,user_label,enodeb_id,gnodeb_id
2,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:30,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
3,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:26:39,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:10,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
5,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-
6,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",-,Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",...,-,2026-07-07 19:27:16,-,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,-,Signaling system,-,3537,-

Handling missing values

### Evaluating Missing Values with '-' as Missing Data

As suggested, we will now consider '-' as a missing value and replace it with `NaN` across the DataFrame before re-checking for missing values.

In [14]:
# Replace all '-' values with NaN in the DataFrame
df.replace('-', pd.NA, inplace=True)

# Re-calculate missing values after replacing '-' with NaN
missing_values_rechecked = df.isnull().sum()
missing_values_rechecked = missing_values_rechecked[missing_values_rechecked > 0].sort_values(ascending=False)

print("Columns with missing values (including '-' as NaN) and their counts:")
display(missing_values_rechecked)

# Display the DataFrame info again to see updated counts
display(df.info())

Columns with missing values (including '-' as NaN) and their counts:

maintenance_region         999999
link_type                  999999
trouble_ticket_id          999999
user_label                 999999
link_name                  999999
operation_impact_flag      999999
request_id                 999999
comment                    999545
common_alarm_identifier    995907
gnodeb_id                  993316
rru_name                   972723
alarm_type                 440422
enodeb_id                  425701
bbu_name                   423854
dev_root_csn               405768
object_type                241266
additional_information     170627
location_information          130
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 2 to 1000000
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   alarm_type                     559577 non-null  object
 1   severity                       999999 non-null  object
 2   occurred_on                    999999 non-null  datetime64[ns]
 3   cleared_on                     999999 non-null  datetime64[ns]
 4   alarm_id                       999999 non-null  object
 5   mo_name                        999999 non-null  object
 6   comment                        454 non-null     object
 7   alarm_name                     999999 non-null  object
 8   location_information           999869 non-null  object
 9   additional_information         829372 non-null  object
 10  alarm_duration                 999999 non-null  object
 11  alarm_source                   999999 non-null  object
 12  acknowledged_by                999999 non-null  object
 13  acknowledged_on                999999 non-null  datetime64[ns]
 14  acknowledgement_status         999999 non-null  object
 15  associated_alarm_group_id      999999 non-null  object
 16  auto_clear                     999999 non-null  object
 17  bbu_name                       576145 non-null  object
 18  clearance_status               999999 non-null  object
 19  clearance_type                 999999 non-null  object
 20  cleared_by                     999999 non-null  object
 21  common_alarm_identifier        4092 non-null    object
 22  dev_root_csn                   594231 non-null  object
 23  equipment_alarm_serial_number  999999 non-null  object
 24  external_resource_id           999999 non-null  object
 25  link_name                      0 non-null       object
 26  link_type                      0 non-null       object
 27  log_serial_number              999999 non-null  object
 28  maintenance_region             0 non-null       object
 29  maintenance_status             999999 non-null  object
 30  ne_address                     999999 non-null  object
 31  ne_type                        999999 non-null  object
 32  object_type                    758733 non-null  object
 33  operation_impact_flag          0 non-null       object
 34  rru_name                       27276 non-null   object
 35  received_on                    999999 non-null  datetime64[ns]
 36  request_id                     0 non-null       object
 37  subnet                         999999 non-null  object
 38  toggling_times                 999999 non-null  object
 39  trouble_ticket_id              0 non-null       object
 40  type                           999999 non-null  object
 41  user_label                     0 non-null       object
 42  enodeb_id                      574298 non-null  object
 43  gnodeb_id                      6683 non-null    object
dtypes: datetime64[ns](4), object(40)
memory usage: 335.7+ MB

None

### Droping irrelevant columns based on Threshold

we will now drop columns that have more than 95% missing values, with the exception of `gnodeb_id` which is to be retained. For the remaining columns with missing values, including `gnodeb_id`, we will fill them appropriately.


`gnodeb_id` is required for 5G connection detections therefore it is retained.

In [15]:
total_rows = df.shape[0]
missing_percentage = (df.isnull().sum() / total_rows) * 100

# Identify columns to drop (more than 95% missing) but exclude 'gnodeb_id'
columns_to_drop = missing_percentage[missing_percentage > 95].index.tolist()

if 'gnodeb_id' in columns_to_drop:
    columns_to_drop.remove('gnodeb_id')
    print("Retaining 'gnodeb_id' as per user request, even though it has >95% missing values.")

if columns_to_drop:
    df.drop(columns=columns_to_drop, inplace=True)
    print(f"Dropped columns with >95% missing values (excluding gnodeb_id): {columns_to_drop}")
else:
    print("No columns to drop based on the >95% missing value threshold (excluding gnodeb_id).")

# Now, re-evaluate missing values and fill them for remaining columns
# For object columns, fill with 'Unknown'
for col in df.select_dtypes(include=['object']).columns:
    if df[col].isnull().any():
        df[col].fillna('Unknown', inplace=True)

# For other types (e.g., numeric), we might need different strategies, but for now assuming object types cover the rest.
# If there are datetime columns with NaT, they will remain as such, which is acceptable.

print("\nMissing values after dropping columns and filling object types:")
missing_values_final = df.isnull().sum()
missing_values_final = missing_values_final[missing_values_final > 0].sort_values(ascending=False)

if missing_values_final.empty:
    print("All missing values have been handled.")
else:
    display(missing_values_final)

display(df.head())

Retaining 'gnodeb_id' as per user request, even though it has >95% missing values.
Dropped columns with >95% missing values (excluding gnodeb_id): ['comment', 'common_alarm_identifier', 'link_name', 'link_type', 'maintenance_region', 'operation_impact_flag', 'rru_name', 'request_id', 'trouble_ticket_id', 'user_label']

/tmp/ipykernel_721/2026937173.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna('Unknown', inplace=True)

Missing values after dropping columns and filling object types:
All missing values have been handled.

,alarm_type,severity,occurred_on,cleared_on,alarm_id,mo_name,alarm_name,location_information,additional_information,alarm_duration,...,maintenance_status,ne_address,ne_type,object_type,received_on,subnet,toggling_times,type,enodeb_id,gnodeb_id
2,Root alarm,Critical,2026-07-07 19:26:23,2026-07-07 19:26:33,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 0 minutes 10 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:26:30,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown
3,Root alarm,Critical,2026-07-07 19:26:14,2026-07-07 19:27:36,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 22 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:26:39,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown
4,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 10 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:27:10,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown
5,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:50,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 3 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:27:16,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown
6,Root alarm,Critical,2026-07-07 19:26:47,2026-07-07 19:27:57,29240,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...",Cell Unavailable,"eNodeB Function Name=BDPAS2_L_Passara_town_Ba,...","RAT_INFO=GL, AFFECTED_RAT=L, DID=NULL, Cumulat...",0 hours 1 minutes 10 seconds,...,NORMAL,10.71.75.146,BTS3900,Cell,2026-07-07 19:27:16,ROOT/RAN Subnet/BTS/BTS3900 - Co-MPT/GUL,0,Signaling system,3537,Unknown

In [16]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 2 to 1000000
Data columns (total 34 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   alarm_type                     999999 non-null  object
 1   severity                       999999 non-null  object
 2   occurred_on                    999999 non-null  datetime64[ns]
 3   cleared_on                     999999 non-null  datetime64[ns]
 4   alarm_id                       999999 non-null  object
 5   mo_name                        999999 non-null  object
 6   alarm_name                     999999 non-null  object
 7   location_information           999999 non-null  object
 8   additional_information         999999 non-null  object
 9   alarm_duration                 999999 non-null  object
 10  alarm_source                   999999 non-null  object
 11  acknowledged_by                999999 non-null  object
 12  acknowledged_on                999999 non-null  datetime64[ns]
 13  acknowledgement_status         999999 non-null  object
 14  associated_alarm_group_id      999999 non-null  object
 15  auto_clear                     999999 non-null  object
 16  bbu_name                       999999 non-null  object
 17  clearance_status               999999 non-null  object
 18  clearance_type                 999999 non-null  object
 19  cleared_by                     999999 non-null  object
 20  dev_root_csn                   999999 non-null  object
 21  equipment_alarm_serial_number  999999 non-null  object
 22  external_resource_id           999999 non-null  object
 23  log_serial_number              999999 non-null  object
 24  maintenance_status             999999 non-null  object
 25  ne_address                     999999 non-null  object
 26  ne_type                        999999 non-null  object
 27  object_type                    999999 non-null  object
 28  received_on                    999999 non-null  datetime64[ns]
 29  subnet                         999999 non-null  object
 30  toggling_times                 999999 non-null  object
 31  type                           999999 non-null  object
 32  enodeb_id                      999999 non-null  object
 33  gnodeb_id                      999999 non-null  object
dtypes: datetime64[ns](4), object(30)
memory usage: 259.4+ MB

None